env:
  commonjs: true
  browser: true
  es6: true
  webextensions: true

globals:
  browser: true

extends:
  - eslint:recommended
  - plugin:mozilla/recommended

plugins:
  - mozilla
  - promise

root: true

rules:
  curly: error
  brace-style: [error, 1tbs]
  indent: [error, 2, { SwitchCase: 1 }]
  eqeqeq: error
  no-console: [error, { allow: [debug, error, info, trace, warn] }]
  no-var: error # TODO: change to "error"
  prefer-const: error # TODO: change to "error"
  quotes: [error, single]
  quote-props: [error, as-needed]
  one-var: [error, never]

  promise/always-return: off
  promise/avoid-new: off
  promise/catch-or-return: error
  promise/no-callback-in-promise: off
  promise/no-native: off
  promise/no-nesting: off
  promise/no-promise-in-callback: off
  promise/param-names: error
